version: '3.7'

services:
  flask-app:
    container_name: 'flask-app'
    build:
      context: .
      dockerfile: Dockerfile
    image: flask-app
    volumes:
      - type: bind
        source: /home/ubuntu/contentData
        target: /usr/src/contentData
    networks:
      - docker-network
    restart: unless-stopped
  nginx-reverse-proxy:
    container_name: 'nginx-reverse-proxy'
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/production.conf:/etc/nginx/conf.d/default.conf
      - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/impressionist-application-east-1.crossley.tech/fullchain.pem:/etc/letsencrypt/live/impressionist-application-east-1.crossley.tech/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/impressionist-application-east-1.crossley.tech/privkey.pem:/etc/letsencrypt/live/impressionist-application-east-1.crossley.tech/privkey.pem
      - /docker-volumes/data/letsencrypt:/data/letsencrypt
    depends_on: 
      - flask-app
    links:
      - "flask-app"
    networks:
      - docker-network
    restart: unless-stopped

networks:
  docker-network:
    driver: bridge

    