version: '3'

services:

  user-database:
    build:
      context: .
      dockerfile: Dockerfile
    image: user-database
    ports:
      - "3001:3001"
    container_name: user-database
    restart: unless-stopped
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx:mainline
    container_name: nginx
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - user-database