version: '3.1'

services:
  user-database:
    container_name: 'user-database'
    build:
      context: .
      dockerfile: Dockerfile
    image: user-database
    networks:
      - docker-network
    restart: unless-stopped
  nginx-reverse-proxy:
    container_name: 'nginx-reverse-proxy'
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/production.conf:/etc/nginx/conf.d/default.conf
      - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/impressionist-user-db-api-east-1.crossley.tech/fullchain.pem:/etc/letsencrypt/live/impressionist-user-db-api-east-1.crossley.tech/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/impressionist-user-db-api-east-1.crossley.tech/privkey.pem:/etc/letsencrypt/live/impressionist-user-db-api-east-1.crossley.tech/privkey.pem
      - /docker-volumes/data/letsencrypt:/data/letsencrypt
    depends_on: 
      - user-database
    links:
      - "user-database"
    networks:
      - docker-network
    restart: unless-stopped

networks:
  docker-network:
    driver: bridge

    